### ISSUE TITLE
Image size?

### ISSUE THREAD

**Issue by CarlosGrohmann** [pjhartzell/GPIV#1]
Hello, thanks for sharing this tool. I'm trying to run it on a dataset I have for a dune field in South Brazil. The examples worked fine, but with my data, it crashes:

`guano:GPIV-master$ gpiv piv dem_als_bilinear_step_2.tif dem_sfm_bilinear_step_2.tif 200 200
Computing PIV.  
/usr/local/lib/python3.7/site-packages/skimage/feature/template.py:165: RuntimeWarning: invalid value encountered in greater  
  mask = denominator > np.finfo(np.float64).eps  
Traceback (most recent call last):  
  File "/usr/local/bin/gpiv", line 10, in <module>  
    sys.exit(cli())  
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__  
    return self.main(*args, **kwargs)  
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main  
    rv = self.invoke(ctx)  
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke  
    return _process_result(sub_ctx.command.invoke(sub_ctx))  
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke  
    return ctx.invoke(self.callback, **ctx.params)  
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke  
    return callback(*args, **kwargs)  
  File "/usr/local/lib/python3.7/site-packages/gpiv.py", line 45, in piv  
    propagate, output_base_name)  
  File "/usr/local/lib/python3.7/site-packages/piv_functions.py", line 30, in piv  
    False, output_base_name)  
  File "/usr/local/lib/python3.7/site-packages/piv_functions.py", line 135, in run_piv  
    if (correlation_max[0][0]==0 or  
IndexError: index 0 is out of bounds for axis 0 with size 0  
guano:GPIV-master$`

image size is 1849 x 3440, would that be the issue?

thanks

**Comment by pjhartzell** [comment]
Thanks for giving it a spin! Image size should not be an issue. It looks like a divide by zero problem, which means my current check for that condition is not up to par. Can you send me your images so I can test and correct the problem? If you'd prefer, you can send them directly to me at preston.hartzell@gmail.com.

**Comment by CarlosGrohmann** [comment]
The images are a bit large but these links should work for now:

https://www.dropbox.com/s/8c6j6m2qmsicxl2/dem_als_bilinear_step_2.tif?dl=0

https://www.dropbox.com/s/2rrf089j0i00wro/dem_sfm_bilinear_step_2.tif?dl=0

**Comment by pjhartzell** [comment]
Thanks. Will look into this tonight.

**Comment by pjhartzell** [comment]
The issue appeared to be the blank areas that contain NaN values. The correlation function doesn't like them. For now, I simply augmented an existing if statement to test for the presence of NaNs and to skip the correlation computation if they exist.

**Comment by CarlosGrohmann** [comment]
It works!
thanks for the help. 
BTW, my system was a bit stubborn and trying to run it via python2, so I had to make sure that both 
```
number_horizontal_computations 
number_vertical_computations
```
were integers, otherwise the range() function in python2 would fail

 
![Figure_1](https://user-images.githubusercontent.com/1870265/65776931-71baa480-e119-11e9-8b9d-12d648eb2c88.png)

**Comment by pjhartzell** [comment]
Cool. Do those vectors align with what you expect? They look large and randomly directed...

I had not considered the project being run with Python 2. Is there a reason why an environment that matches the one spec'd in the `gpiv.yml` file can not be created and used? I'm relatively new to both Python and sharing my work with others, so that is a serious (not snarky) question. 🙂
